#!/bin/bash

export CEX_ROOT="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
cd $CEX_ROOT

cmd=$1
shift
args="$@"

function run_cmd
{
    local cmd_=$1

    if [ ${cmd_:0:1} == '"' ]; then
        cmd_=$(echo "$cmd_" | sed -e 's/^"//' -e 's/"$//')
    fi

    if [ ${cmd_:0:1} == './' ]; then
        echo -e "$cmd_ $args \n"
        $cmd_ $args
    else
        echo -e "$cmd_ $args \n"
        exec $cmd_ $args
    fi

    exit 0
}

function find_cmd
{
    while read n c 
    do
        if [ -z "$n" ]; then
            continue
        fi

        if [ ${n:0:1} == '#' ]; then
            continue
        fi

        if [ "$n" == "$cmd" ] ; then
            echo "$c"
            break
        fi
    done < $1
}

function process_cmd_list
{
    pushd $(dirname $1) > /dev/null

    preload_from_dir preload

    job=$(find_cmd $1)
    if [ ! -z "$job" ]; then
        run_cmd "$job"
    fi

    popd > /dev/null
}

function preload_from_dir
{
    set -a
    for pre in $1/* ; do
        . $pre
    done
    set +a
}

process_cmd_list ${CEX_ROOT}/commands

cex_check_var CEX_APP_ROOT
process_cmd_list ${CEX_APP_ROOT}/commands

echo -e "invalid cmd: $cmd
run: $CEX_APP_NAME --help
"